// modified from what was originally generated by $JBOSS_HOME/bin/wsconsume.sh script
// @javax.xml.bind.annotation.XmlSchema(namespace = "urn:com.redhat.gpe.auditReview:1.0")

// namespace of this annotation now is reverse order of package name
@javax.xml.bind.annotation.XmlSchema(namespace = "domain.bpm_servicetasks.refarch.gpe.redhat.com")
package com.redhat.gpe.refarch.bpm_servicetasks.domain;
