//created on: Apr 13, 2015
package org.acme.insurance.policyquote

import org.acme.insurance.Driver
import org.acme.insurance.Policy
 
rule "SafeYouths"
 
    when
        //conditions
        driver : Driver(age >= 18 && < 25, numberOfAccidents < 1, numberOfTickets <= 1)
	    policy : Policy(price == null, policyType == "AUTO")
    then
        //actions
        modify(policy) {setPrice(450)};
        System.out.println("fired rule " + kcontext.getRule().getName());
 
end