package org.acme.insurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Rejection implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Rejection() {
    }

}