package org.acme.insurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Rejection")
public class Rejection implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "Reason")
    private java.lang.String reason;

    public String getReason() {
        return this.reason;
    }
    public void setReason(String x) {
        this.reason = x;
    }

    public Rejection() {
    }

}
